INSERT INTO carriers (code, name) VALUES
    ('9E', 'Endeavor Air Inc.'),
    ('AA', 'American Airlines Inc.'),
    ('AS', 'Alaska Airlines Inc.'),
    ('B6', 'JetBlue Airways'),
    ('CO', 'Continental Air Lines Inc.'),
    ('DH', 'Independence Air'),
    ('DL', 'Delta Air Lines Inc.'),
    ('EA', 'Eastern Air Lines Inc.'),
    ('EV', 'ExpressJet Airlines Inc.'),
    ('F9', 'Frontier Airlines Inc.'),
    ('FL', 'AirTran Airways Corporation'),
    ('G4', 'Allegiant Air'),
    ('HA', 'Hawaiian Airlines Inc.'),
    ('HP', 'America West Airlines Inc.'),
    ('KH', 'Aloha Air Cargo'),
    ('ML(1)',  'Midway Airlines Inc.'),
    ('MQ', 'Envoy Air'),
    ('NK', 'Spirit Air Lines'),
    ('NW', 'Northwest Airlines Inc.'),
    ('OH', 'PSA Airlines Inc.'),
    ('OO', 'SkyWest Airlines Inc.'),
    ('PA(1)',  'Pan American World Airways (1)'),
    ('PI', 'Piedmont Aviation Inc.'),
    ('PS', 'Ukraine International Airlines'),
    ('TW', 'Trans World Airways LLC'),
    ('TZ', 'ATA Airlines d/b/a ATA'),
    ('UA', 'United Air Lines Inc.'),
    ('US', 'US Airways Inc.'),
    ('VX', 'Virgin America'),
    ('WN', 'Southwest Airlines Co.'),
    ('XE', 'ExpressJet Airlines Inc. (1)'),
    ('YV', 'Mesa Airlines Inc.'),
    ('YX', 'Republic Airline');
